vti_encoding:SR|utf8-nl
vti_version:SW|5.0.2.2623
vti_timelastmodified:TR|01 Feb 2021 06:15:52 -0000
vti_author:SR|DESKTOP-NR5SSHF\\Austins-6200
vti_modifiedby:SR|DESKTOP-NR5SSHF\\Austins-6200
vti_nexttolasttimemodified:TR|01 Feb 2021 06:15:52 -0000
vti_timecreated:TR|01 Feb 2021 06:20:00 -0000
vti_extenderversion:SR|5.0.2.2623
vti_syncwith_localhost\\c\:\\users\\austins-6200\\documents\\my webs\\myweb/c\:/users/austins-6200/documents/my webs/myweb:TR|01 Feb 2021 06:15:52 -0000
vti_lineageid:SR|{56035B64-A46C-4E00-A501-5675B538C24D}
vti_cacheddtm:TX|01 Feb 2021 06:20:00 -0000
vti_filesize:IR|8217
vti_backlinkinfo:VX|inventory_interface/Results/results_page.asp
